### PR TITLE
Fix/empty emails

### LINKED ISSUE #1780: The widget was sent to the recipient who was removed from the list of recipients.
Steps to produce :
1. Login to zafira ;
2. Click [Boards] button in the right sidebar ;
3. Click [General] button , or any other dashboard ;
4. Click (Three dots) button in the right top corner of the required widget ;
5. Click [Send by email] button ;
6. Insert into "Recipients" field any valid available email ;
7. Delete address from "Recipients" field ; 
8. Click [Send] button .
9. Check according email's inbox .

Actual result : 
User able to sent widget with empty "Recipients" field ;
"Email was successfully sent !" notification appears in the right bottom corner ;
After user clicks [Send] button , Recipients value became "(1)" for little moment ;
According email box received according widget .
[DEMO](https://drive.google.com/open?id=17-r9EH5ZD5PiKV7WDroGVpR0lcZFZfEf)

Expected result : 
User unable to sent widget with empty "Recipients" field ;
Removed email does not receive email with widget .

### PR DESCRIPTION
**Pull request by Ageenkooo**
Fixes qaprosoft/zafira#1780

### CODE REVIEW

File: client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js [hunk 1]
```diff
@@ -109,16 +109,18 @@ const dashboardEmailModalController = function dashboardEmailModalController($sc
     }
 
     $scope.checkAndTransformRecipient = function (currentUser) {
-        var user = {};
+        let user = {};
+
         if (currentUser.username) {
             user = currentUser;
```
Comment (danymill) [inline client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js]: Improve `currentUser` validation: use typeof at least

**Review by danymill — CHANGES_REQUESTED** [review]

**Review by danymill — APPROVED** [review]
