### PR TITLE
fixed email validation on dashboards

### LINKED ISSUE #1779: User is able to send widget to recipient without email domain .
Steps to produce : 
1. Login to zafira ;
2. Click [Boards] button in the right sidebar ; 
3. Click [General] button , or any other dashboard ; 
4. Click (Three dots) button in the right top corner of the required widget ; 
5. Click [Send by email] button ; 
6. Insert into "Recipients" field one symbol (digit , letter , spec.symbol) ;
7. Click [Send] button .

Actual result : 
User able to send widget to the (in my opinion invalid recipient) ;
"Email was successfully sent !" notification appears in the right bottom corner .
[DEMO](https://drive.google.com/open?id=1gN49xxy3tif7jdEN_u89Yx2SwEYfAyqZ)

Expected result : 
User unable to send widget to the invalid recipients ;
User able to send widgets to already exist zafira users with attached email ;
User able to send widgets (via email) to recipients with email domain only .

### PR DESCRIPTION
**Pull request by Ageenkooo**
fixes qaprosoft/zafira#1779

### CODE REVIEW

File: client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js [hunk 1]
```diff
@@ -87,7 +105,7 @@ const dashboardEmailModalController = function dashboardEmailModalController($sc
                     if (! rs.data.results.length) {
                         stopCriteria = criteria;
                     }
-                    return rs.data.results.filter(searchFilter(user));
+                    return rs.data.results.filter(searchFilter(user)).filter((user) => user.email);
```
Comment (danymill) [inline client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js]: Please refactor `searchFilter` and `querySearch`

**Review by danymill — CHANGES_REQUESTED** [review]

File: client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js [hunk 2]
```diff
@@ -46,11 +46,29 @@ const dashboardEmailModalController = function dashboardEmailModalController($sc
...
-        sendEmail(EMAIL_TYPES[TYPE].locator, angular.copy($scope.email)).then(function () {
-            $scope.hide();
-        });
+        if (areAllEmailsValid()) {
+            sendEmail(EMAIL_TYPES[TYPE].locator, angular.copy($scope.email)).then(function () {
+                $scope.hide();
+            });
+        } else {
+            messageService.error('Invalid email format');
+            return;
```
Comment (danymill) [inline client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js]: Don't allow to add invalid email instead of displaying error on sent action

**Review by danymill — CHANGES_REQUESTED** [review]

File: client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js [hunk 3]
```diff
@@ -77,48 +83,49 @@ const dashboardEmailModalController = function dashboardEmailModalController($sc
...
+            
             user.email = currentUser;
-            $scope.email.recipients.push(user.email);
-            $scope.users.push(user);
+        } else if (currentUser.email) {
+            user = currentUser;
         }
+
+        $scope.email.recipients.push(user.email);
+        $scope.users.push(user);
```
Comment (danymill) [inline client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js]: What will happen if `currentUser` is a `Number`?

**Comment by Ageenkooo** [comment]
@danymill improved; fixed case for number input

File: client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js [hunk 4]
```diff
@@ -77,48 +83,50 @@ const dashboardEmailModalController = function dashboardEmailModalController($sc
...
         } else {
-            user.email = currentUser;
-            $scope.email.recipients.push(user.email);
-            $scope.users.push(user);
+            if (!isValidRecipient(currentUser)) {
+                messageService.error('Invalid email format');
+
+                return null;
+            }
+            if (typeof currentUser === 'string') {
```
Comment (danymill) [inline client/app/_dashboards/dashboard-email-modal/dashboard-email-modal.controller.js]: Redundant checking

**Review by danymill — CHANGES_REQUESTED** [review]

**Review by danymill — APPROVED** [review]
